# Generated by Django 5.1.7 on 2025-04-01 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('copyid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'book_copy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LibraryBranch',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('lname', models.CharField(blank=True, null=True)),
                ('laddress', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'library_branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mid', models.IntegerField(primary_key=True, serialize=False)),
                ('mname', models.CharField(blank=True, null=True)),
                ('maddress', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('mid', models.OneToOneField(db_column='mid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='members.member')),
                ('loandate', models.DateField()),
                ('returndate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan',
                'managed': False,
            },
        ),
    ]
